const LandingAIInsights = () => {
  return (
    <div className="rounded-2xl border border-blue-500/30 bg-slate-900 p-6 shadow-xl">
      <div className="mb-6 flex items-center gap-3">
        <div className="rounded-full bg-blue-500/10 p-2 text-blue-400">
          AI
        </div>
        <h2 className="text-xl font-bold">AI Insights</h2>
      </div>

      <div className="space-y-5">
        <div className="flex gap-4 rounded-xl bg-slate-950 p-4">
          <p className="text-slate-300">
            Sign in and upload your statement to receive insights generated by Gemini from your own transactions.
          </p>
        </div>
      </div>
    </div>
  );
};

export default LandingAIInsights;
