import Navbar from "../../components/layout/Navbar";
import Hero from "../../components/landing/Hero";
import Features from "../../components/landing/Features";
import Stats from "../../components/landing/Stats";
import Container from "../../components/common/Container";
import SectionTitle from "../../components/common/SectionTitle";

const Landing = () => {
  return (
    <>
      <Navbar />
      <Hero />
      <Features />
      <Stats />

      <section id="about" className="scroll-mt-20 border-t border-slate-800/70 py-28">
        <Container>
          <div className="mx-auto max-w-3xl text-center">
            <SectionTitle
              title="About FinSight AI"
              subtitle="FinSight AI turns everyday transaction data into a clearer picture of your financial life."
            />
            <p className="mt-8 text-lg leading-8 text-slate-400">
              Upload a CSV or PDF statement, review your credited and debited transactions, and receive practical insights generated by Gemini. Your dashboard brings spending patterns, categories, and next steps together in one focused workspace.
            </p>
          </div>
        </Container>
      </section>
    </>
  );
};

export default Landing;